### ISSUE TITLE
Howto execute bash Script?

### ISSUE THREAD

**Issue by carlymx** [Salandora/OctoPrint-SystemCommandEditor#10]
Hello,

I have a script to start 'Motion' and I would like to know what would be the command line that dev use to make the plugin work.

Everything I've tried sends me the same error, when the terminal works perfectly.

```
Error:
The command "WebCam ON" could not be executed.
More...

Command for custom:Start Motion failed with return code 1:
STDOUT: Must be connected to a terminal.
STDERR: 
```
The Script is very simple and as it says it works perfectly in the terminal:

```
#!/bin/bash
### BEGIN INIT INFO
# Provides: motion_start
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start Motion
# Description:
#
### END INIT INFO

screen -S motion -A -m \
motion \

```
The command lines I use in the plugins are the following:

```
sudo  /home/orangeprint/scripts/motion.sh
sudo bash /home/orangeprint/scripts/motion.sh
```
I hope you can help me thanks

**Comment by Salandora** [comment]
Well, both of your commands seem to work.
But problem seems to be with screen requireing a bit more then octoprint offers it.

Maybe you should convert your script to either a systemd service file or a real initd service file and let octoprint run "service start <name of your service>"
