### ISSUE TITLE
i can't run cd commands 

### ISSUE THREAD

**Issue by The-Math-God** [Salandora/OctoPrint-SystemCommandEditor#18]
hi i have an issue everytime i run this command "cd uhubctl" i get this error

Command for custom:p3 off failed with return code 2:
STDOUT: 
STDERR: /bin/sh: 1: cd: can't cd to uhubctl

but when i run the exact same command through putty it works fine what am i doing wrong

**Comment by Salandora** [comment]
Uhm can you show the full script / command also, maybe try the absolute path instead of relative.

**Comment by The-Math-God** [comment]
cd uhubctl ; ./uhubctl -l 1-1.1 -a 0 -p 3 and cd uhubctl ; ./uhubctl -l 1-1.1 -a 0 -p 3

**Comment by Salandora** [comment]
have you tried to use the absolute path?
Additionally you maybe want to put that into a .sh file if not already done.

**Comment by The-Math-God** [comment]
i got it working a just had to type it like this cd /home/pi/uhubctl ; ./uhubctl -l 1-1.1 -a 0 -p 3 and it worked thanks for the help :)

**Comment by Salandora** [comment]
Closing because it's workin.
