### ISSUE TITLE
only one (system)command works

### ISSUE THREAD

**Issue by Werja** [Salandora/OctoPrint-SystemCommandEditor#2]
Hello,
I have a problem with the SystemCommand Plugin.
I use octoprint 1.2.6 on Octopi. 
When one system command is created it works fine, but when i create a second command the properties from the first command will be override.

**Comment by Salandora** [comment]
Thats interesting can you please provide the settings for both commands you created. Will try to replicate the problem then.

**Comment by Werja** [comment]
I need two commands to contro my webcam with a servo. There are little
python scripts to do that.

I create the first command:
    name: Kamera nach oben
    aktion: empty
    command:sudo python /home/pi/scripts/kamera_nach_oben.py
    no confirmation string
-> bestätigen
create command two:
    name: Kamera nach unten
    aktion: empty
    command:sudo python /home/pi/scripts/kamera_nach_unten.py
    no confirmation string
-> bestätigen
save settings

Now both commands are available over the system tab in octoprint, but
only the first system-command will executed on both items.
So i go back to settings and edit the "Kamera nach unten" item and found
this wrong setting:
name: Kamera nach oben
command:sudo  python /home/pi/scripts/kamera_nach_oben.py

btw: Is thre a option to prevent the default confirmation?

Am 24.09.2015 um 17:30 schrieb Salandora:

**Comment by Salandora** [comment]
No wonder, you need to set "aktion" to a unique name.
Like "cameraup" and "cameradown"

**Comment by Werja** [comment]
Thanks for your reply. The commands are working now.
Is there an option to prevent the default confirmation?

**Comment by Salandora** [comment]
I believe no.
