### ISSUE TITLE
Conflict with DragonOrder plugin

### ISSUE THREAD

**Issue by jneilliii** [Salandora/OctoPrint-SystemCommandEditor#20]
@Salandora, would it be possible to upgrade the ui.sortable library to jQuery UI v1.12.1?  It seems that your sortable library is causing conflict with my DragonOrder plugin. See [here](https://github.com/jneilliii/OctoPrint-DragonOrder/issues/6).

**Comment by Salandora** [comment]
@jneilliii sure but as I'm actually not doing any active development on any of my plugins, due to lack of time and interest (not even having a proper development environment right now), I would need someone to make a PR.
