### ISSUE TITLE
Always the first command get executed

### ISSUE THREAD

**Issue by ps915** [Salandora/OctoPrint-SystemCommandEditor#3]
i am using 1.2.8

I have set 3 different commands but everythime i execute them, the first command will be executed.

![2](https://cloud.githubusercontent.com/assets/3420935/12869859/81cc7dfe-cd2b-11e5-8332-722042bbec56.PNG)
 I also can not edit it. If i click in on the last two commands and want to edit them, always the first one wil be edited.
![3](https://cloud.githubusercontent.com/assets/3420935/12869860/83d4a78e-cd2b-11e5-9d7b-9dad7798d0ab.PNG)

This is also strange: if i remove your Plugin, then also the "System" Button with the old 3 commands is still there. The Stock System Button with its command is not there. :-(

![1](https://cloud.githubusercontent.com/assets/3420935/12869858/7fdda9fa-cd2b-11e5-852a-0086ba144bf6.PNG)

**Comment by Salandora** [comment]
Duplicate of #2 -> user mistake
