### ISSUE TITLE
I cant configure Reboot button

### ISSUE THREAD

**Issue by McKaNaN** [Salandora/OctoPrint-SystemCommandEditor#6]
I like put a "Reboot" button in OctoPrint but I cant and I dont understand.

I put this text in configuration menu:

name: reboot
action: reboot
command: sudo reboot

But dont work. Shows me a message:

_The command "Reboot" could not be executed.

Command failed with return code 1:
STDOUT: 
STDERR: sudo: no tty present and no askpass program specified_

What can I do?

**Comment by Salandora** [comment]
Well that's a problem with your sudoers config,
sudo is asking for a password which can't be supplied.

you'll need to adapt the sudoers file to get it working.
maybe a  "sudo shutdown -r now" is already configured correctly

**Comment by McKaNaN** [comment]
Yes! Work it!
The problem was the sudoers permissions.

Thanx!!!
